### ISSUE TITLE
"Syntax error at '\n'" on a valid C macro.

### ISSUE THREAD

**Issue by GoogleCodeExporter** [ctypesgen/ctypesgen#25]
```
Hi,

The C parser in ctypesgen (version 0.r125) gives a syntax error on some header 
files that GCC accepts. Example output:

    Error: /usr/include/libxml2/libxml/xmlstring.h:35: Syntax error at '\n'

This message comes from the ctypesgencore.parser.cgrammar.p_error function.

To reproduce, create a file named "test.h" containing:

    typedef unsigned char xmlChar;
    #define BAD_CAST (xmlChar *)

(This is extracted from xmlstring.h)
Then, run: ctypesgen.py -o test.py test.h

This error interrupts everything and test.py ends up with no content generated 
from header files. (It has no mention of xmlChar, BAD_CAST, or anything else.)

It seems that the parser sees this #define as a macro with a xmlChar parameter 
and a missing definition is missing, while it is really a parameter-less macro.

ctypesgencore.parser.yacc.Parser.parse does something like this:

    token = actions.get((statestack[-1], lookahead.type), None)

When the error is triggered, statestack[-1] is 293 and lookahead.type is 
PP_END_DEFINE. I guess that the fix should go somewhere in the cgrammar module, 
but I had no idea where to go from there.
```

Original issue reported on code.google.com by `simon.sa...@kozea.fr` on 3 Dec 2011 at 5:29

**Comment by fgrie** [comment]
Similar problem here, please reopen.
Platform is Windows 10, using gcc from mingw64 distribution.
It even happens when parsing a empty header. Preprocessed output stored using the save_preprocessed_headers option is  attached:
[preprocessed.txt](https://github.com/davidjamesca/ctypesgen/files/5532035/preprocessed.txt)

Maybe you can validate if this preprocessor output can be parsed on you machine correctly to reproduce the problem.

INFO: Status: Preprocessing C:\Users\Username\AppData\Local\Temp\tmpvrtclbxc.h
INFO: Status: gcc -E -U __GNUC__ -dD "-Dinline=" "-D__inline__=" "-D__extension__=" "-D__const=const" "-D__asm__(x)=" "-D__asm(x)=" "-DCTYPESGEN=1" "C:\Users\Username\AppData\Local\Temp\tmpvrtclbxc.h"
INFO: Status: Saving preprocessed headers to c:\Users\Username\preprocessed.txt.
INFO: Status: Parsing C:\Users\Username\AppData\Local\Temp\tmpvrtclbxc.h
ERROR: <built-in>:332: Syntax error at '\n'
ERROR: <built-in>:333: Syntax error at '\n'
ERROR: <built-in>:334: Syntax error at '\n'
ERROR: <built-in>:335: Syntax error at '\n'
ERROR: <built-in>:336: Syntax error at '\n'
ERROR: <built-in>:337: Syntax error at '\n'
ERROR: <built-in>:338: Syntax error at '\n'
ERROR: <built-in>:339: Syntax error at '\n'
