### ISSUE TITLE
Recognize structs from common header files in different wrapper modules

### ISSUE THREAD

**Issue by manolis-andr** [ctypesgen/ctypesgen#86]
### Problem
ctypesgen generates wrapper ctypes-compatible classes for each necessary C struct (necessary structs: structs defined in the header to be wrapped or dependent structs of other included headers). When we have 2 header files that reference a struct from a common header file (i.e. both headers reference the same struct), their wrappers will both define the same wrapper class (same name and attributes). However, since the wrapper classes are in 2 different Python modules, they have essentially a different Python type, and thus one cannot use them interchangeably when types matter.

This is the case of calling a function provided by wrapper `a` with a wrapped-struct-class argument from wrapper `b`. ctypesgen sets the `argtypes` of a function using types defined in the same module, so trying to pass any argument from a different module will fail to pass the `argtypes` type-checking.

### Basic Example:
`common.h`
```
struct mystruct {
	int a;
};
```
`a.h` includes `common.h` and declares `void foo(struct mystruct *m)`, `a.c` implements it and `liba.so` is a shared library exporting `foo`.
`b.h` includes `common.h` and declares `void bar(struct mystruct *m)`, `b.c` implements it and `libb.so` is a shared library exporting `bar`.
After generating wrappers for `a.h` (`a.py`) and `b.h` (`b.py`), one can use the following script to highlight the problem.

`run.py:`
```
import ctypes                                                                   
import a                                                                        
import b                                                                        
                                                                                
m = b.struct_mystruct()                                                         
b.bar(ctypes.byref(m)) # works                                                          
a.foo(ctypes.byref(m)) # ctypes.ArgumentError                                                          

m = a.struct_mystruct()                                                         
a.foo(ctypes.byref(m)) # works                                                          
b.bar(ctypes.byref(m)) # ctypes.ArgumentError
```

### Solution
Do you think that recognizing wrapped struct classes that originate from the same header file would be a nice-to-have feature?

One approach to implement it would be to hash the file from which a struct derives (hash the C header), and for wrapper classes that have a hash common to the hash of the `argtypes` argument type, we will allow passing the object to the function. The latter can be implemented by overriding the `from_param()` method of the wrapped struct classes. The hash would resolve any filename conflicts or different versions of the same header file. To also allow passing pointers to structs or passing structs by reference, the `ctypes.POINTER()` has to be overridden as well.

Thanks in advance for considering this proposal and I would be happy to provide a patch in case you deem it worthy.

**Comment by Alan-R** [comment]
I presume you know you can cast it to the appropriate type so ctypes doesn't complain. I understand that you're asking for an enhancement so you don't have to do that.

**Comment by nilason** [comment]
With the addition of `--no-embed-preamble` option, I believe this issue may be closed.

**Comment by nilason** [comment]
Closing this. Please reopen if the `--no-embed-preamble` option doesn't solve your issue.

**Comment by mara004** [comment]
I incidentally came across the code area in question while experimenting locally in the course of #162, and feel very queasy about it. It's strange this was merged without any questioning of the change.

The change adds significant confusion and obscurity to the code, with a lack of explaining comments (the code is incredibly hard to understand without the info from this thread). Moreover, I'd prefer to stay as close to pure `ctypes` as possible and avoid garbling the code with wonky hacks like selective `POINTER` override (see also #26).

**Comment by mara004** [comment]
Update: unfortunately it turns out `--link-modules` is not implemented correctly, ctypesgen just silently overwrites imported symbols. However, this doesn't change the logic: To properly support this use case, the right behavior would be to consider symbols from linked modules in the pipeline and *not* just overwrite them.

**Comment by mara004** [comment]
Apart from that, another problem `--no-embed-preamble` doesn't handle yet is library loading - the current implementation would create multiple library handles if building same-library headers separately.

**Comment by mara004** [comment]
@nilason I have updated the CommonHeaders test to use an actual shared module and avoid symbol duplication in https://github.com/pypdfium2-team/ctypesgen/commit/78a2038945f5ce11fdae367e7ad96c257ab595cf

(It turns out the pipeline dependency resolver managed the symbols correctly, the tough bit was just getting the relative import right at compile time. The caller entrypoint previously did not support this and silently caught the import error, resulting in an empty symbols list, so the symbol sharing failed.)

**Comment by mara004** [comment]
To the OP, also note that this branch of ctypesgen supports binding to multiple libraries in the same file, which I believe is another way to get around this problem.
This actually has an advantage: With module linking you need to resolve the header dependency tree manually, but when using a single file, ctypesgen's dependency resolver will do it for you.

On the other hand, this is currently not present in my fork of ctypesgen since the implementation's a bit problematic: symbol origin resolving is currently tied to binary attribute checks, and loader config is not library specific.
I wonder what would be a better way to implement this, maybe something like this?
```bash
# imaginary, base syntax referring to pypdfium2-team fork
ctypesgen --runtime-libdirs $SHARED_LIBDIRS // -i $HEADERS_LIBA -l a --runtime-libdirs $DIRS_LIBA // -i HEADERS_LIBB -l b --runtime-libdirs $DIRS_LIBB
```
The idea would be to split the `argv` at `//`, treat the first part as base, and any following parts as additional libraries.
This would provide a clear library <-> headers association from the beginning (which would fix the awkwardness of the previous implementation), and allow for passing parameters such as runtime libdirs on a per library basis for tighter config. On the other hand, this would be some task to refactor and (re-)add a significant bit of complexity to CLI, symbol checker and printer.
That said, I'm not sure where in the code we would actually assign the library name to symbols. As things go through the preprocessor in a unified file, I suppose it would require a header path to library name mapping at some point...
