### ISSUE TITLE
Silently failed to parse "__attribute__(packed)" in input header file

### ISSUE THREAD

**Issue by TheCodeArtist** [ctypesgen/ctypesgen#99]
Due to the implcit ` gcc -E -U __GNUC__` hardcoded in https://github.com/davidjamesca/ctypesgen/blob/dd1b3fd57c39071ded73c0d22befc03dcdfa691e/ctypesgen/parser/preprocessor.py#L144

any conditional code in the header files that is written only for GCC compiler is silently ignored by `ctypesgen`.

I noticed this as it resulted in few `__attribute__((__packed__))` in my code being ignored for structs! 😅 

**Why is `-U __GNUC__` required during `ctypesgen`'s preprocessing stage?**
- Is there anyway to avoid it when invoking `ctypesgen`?

**Comment by Alan-R** [comment]
I don't know why this is/was done.  It was before I started on the project, and no one from those days is active on the project today.

My guess is because something didn't work when parsing the GNU headers. Also, it's not clear it would understand attribute "packed", even if that attribute were on. I suspect the meaning of "packed" potentially varies from platform to platform - which would make it harder to do correctly. Some machines can't easily handle byte-aligned integers (for example) - whereas others can, albeit more slowly.

**Comment by TheCodeArtist** [comment]
As a quick experiment,  
i modified line `ctypesgen/ctypesgen/parser/preprocessor.py:144` to...

```cmd += " -dD"```

...and confirmed that such a patched `ctypesgen`   
is able to properly parse and a update the resulting python code  
with the following line each the struct's class.

```struct_<struct-name>._pack_ = 1```

- With this i am able to get my Python code to work on the C struct properly. 🎉 
- Also confirmed that, the built-in testsuite in ctypesgen doesn't complain.

**Would you be interested to merge the change if i submit a pull request for this?**
*(if accepted, this will avoid the need for me to maintain a patched ctypesgen,  
and can ask users to simply install the release deb from here! 🙂)*

**Comment by Alan-R** [comment]
I would be interested in seeing such a patch. Regarding whether I accept it, it depends on what I judge the risk level to be, and whether it fits well into the existing code base.

**Comment by TheCodeArtist** [comment]
Pushed #100 for review.

As you can see, the fix is minimal.
It simply stops the pre-processor from silently stripping-away code defined within `#ifdef __GNUC__`.

With this in place, the existing code in `ctypesgen` now gets a chance to do the right thing. 🙂 

As you rightly pointed out this may have major impact of the behavior.

> the previous behavior of `ctypesgen` can be triggered if desired,
> by explicitly specifying `--cpp "gcc -E -U __GNUC__"` when invoking  `ctypesgen`.
However, i believe the risk is minimal.
Even with this change, anyone interested in the previous behavior can trigger it.

**Comment by davidjamesca** [comment]
I believe "-U __GNUC__" was added because ctypesgen had a hard time parsing advanced GNUC constructs in GCC header files that were spit out by the GCC compiler. This code is way back in [2007 (see commit)](https://github.com/davidjamesca/ctypesgen/commit/2e0229c4f2c4a945d71eb8d2a3b1958d1bc50d32) and the entire codebase was rewritten since then, so it's quite possible it's completely unneeded. I'll defer to Alan-R though.

**Comment by TheCodeArtist** [comment]
Pushed PR https://github.com/ctypesgen/ctypesgen/pull/104 for review.

- It retains the existing/legacy behavior as default.
i.e. ctypesgen implicitly undefines `__GNUC__` while parsing code.

- It introduces a new ctypesgen cmd-line param `--allow-gnu-c`,  
that the user can specify to instruct ctypesgen to NOT undefine `__GNUC__`.

**Comment by TheCodeArtist** [comment]
This enhancement is now supported by https://github.com/ctypesgen/ctypesgen/pull/104
